2024-12-11 22:19:10 - ERROR - [domains_check_MT.py:45] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000179430D6630>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:19:11 - ERROR - [domains_check_MT.py:45] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:19:13 - ERROR - [domains_check_MT.py:45] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:19:13 - ERROR - [domains_check_MT.py:45] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:19:14 - ERROR - [domains_check_MT.py:45] - Request error for forbes.com: HTTPSConnectionPool(host='www.forbes.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:19:15 - ERROR - [domains_check_MT.py:45] - Request error for nginx.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:19:19 - ERROR - [domains_check_MT.py:45] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001794342FB60>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
2024-12-11 22:21:07 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002DBF5E6AF30>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPConnectionPool(host='adobe.com', port=80): Read timed out. (read timeout=1)
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for instagram.com: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for apple.com: HTTPSConnectionPool(host='www.apple.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='goo.gl', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for microsoft.com: HTTPConnectionPool(host='microsoft.com', port=80): Read timed out. (read timeout=1)
None
2024-12-11 22:21:09 - ERROR - [domains_check_MT.py:46] - Request error for maps.google.com: HTTPConnectionPool(host='maps.google.com', port=80): Read timed out. (read timeout=1)
None
2024-12-11 22:21:10 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:21:11 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:21:16 - ERROR - [domains_check_MT.py:46] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002DBF7AB7530>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
2024-12-11 22:22:57 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001DA6706A870>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:22:58 - ERROR - [domains_check_MT.py:46] - Request error for microsoft.com: HTTPConnectionPool(host='microsoft.com', port=80): Read timed out. (read timeout=1)
None
2024-12-11 22:22:59 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:23:00 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:23:02 - ERROR - [domains_check_MT.py:46] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=1)
None
2024-12-11 22:23:05 - ERROR - [domains_check_MT.py:46] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DA67156AB0>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
2024-12-11 22:25:39 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000014124C222D0>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:25:39 - ERROR - [domains_check_MT.py:46] - Request error for maps.google.com: HTTPConnectionPool(host='maps.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:39 - ERROR - [domains_check_MT.py:46] - Request error for microsoft.com: HTTPConnectionPool(host='microsoft.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:40 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:41 - ERROR - [domains_check_MT.py:46] - Request error for mozilla.org: HTTPSConnectionPool(host='mozilla.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for weebly.com: HTTPConnectionPool(host='weebly.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for m.facebook.com: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:42 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:43 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:44 - ERROR - [domains_check_MT.py:46] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:25:47 - ERROR - [domains_check_MT.py:46] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001412330C680>, 'Connection to macromedia.com timed out. (connect timeout=0.5)'))
None
2024-12-11 22:28:59 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217CED28830>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:28:59 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:00 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:00 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:29:00 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:00 - ERROR - [domains_check_MT.py:46] - Request error for flickr.com: HTTPSConnectionPool(host='flickr.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:00 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for open.spotify.com: HTTPSConnectionPool(host='open.spotify.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for weebly.com: HTTPConnectionPool(host='weebly.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for baidu.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for googleblog.com: HTTPSConnectionPool(host='googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for paypal.com: HTTPSConnectionPool(host='www.paypal.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:01 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:03 - ERROR - [domains_check_MT.py:46] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:29:05 - ERROR - [domains_check_MT.py:46] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217CD571460>, 'Connection to macromedia.com timed out. (connect timeout=0.5)'))
None
2024-12-11 22:30:31 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217CEF6F170>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:30:31 - ERROR - [domains_check_MT.py:46] - Request error for plus.google.com: HTTPSConnectionPool(host='workspaceupdates.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:32 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:32 - ERROR - [domains_check_MT.py:46] - Request error for mozilla.org: HTTPSConnectionPool(host='mozilla.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:32 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:33 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:30:34 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:30:34 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:35 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:35 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:30:39 - ERROR - [domains_check_MT.py:46] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217CD5F9580>, 'Connection to macromedia.com timed out. (connect timeout=0.5)'))
None
2024-12-11 22:32:42 - ERROR - [domains_check_MT.py:46] - Request error for google.com: HTTPConnectionPool(host='google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:42 - ERROR - [domains_check_MT.py:46] - Request error for youtube.com: HTTPConnectionPool(host='youtube.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:43 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217D0288170>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:32:43 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:44 - ERROR - [domains_check_MT.py:46] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217D02E6D80>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for microsoft.com: HTTPConnectionPool(host='microsoft.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for flickr.com: HTTPSConnectionPool(host='flickr.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:45 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:32:46 - ERROR - [domains_check_MT.py:46] - Request error for tinyurl.com: HTTPSConnectionPool(host='tinyurl.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:46 - ERROR - [domains_check_MT.py:46] - Request error for zoom.us: HTTPSConnectionPool(host='zoom.us', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:46 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:46 - ERROR - [domains_check_MT.py:46] - Request error for paypal.com: HTTPSConnectionPool(host='www.paypal.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:47 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:32:47 - ERROR - [domains_check_MT.py:46] - Request error for cdc.gov: HTTPSConnectionPool(host='cdc.gov', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for youtu.be: HTTPSConnectionPool(host='youtu.be', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for linkedin.com: HTTPSConnectionPool(host='www.linkedin.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPConnectionPool(host='goo.gl', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for apple.com: HTTPSConnectionPool(host='www.apple.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for maps.google.com: HTTPConnectionPool(host='maps.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for docs.google.com: HTTPConnectionPool(host='docs.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for facebook.com: HTTPSConnectionPool(host='www.facebook.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for en.wikipedia.org: HTTPConnectionPool(host='en.wikipedia.org', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPConnectionPool(host='adobe.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for play.google.com: HTTPSConnectionPool(host='play.google.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for youtube.com: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:38 - ERROR - [domains_check_MT.py:46] - Request error for instagram.com: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:39 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217CF136330>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:35:40 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217CEF08110>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:35:41 - ERROR - [domains_check_MT.py:46] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217D0308A40>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:35:41 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:42 - ERROR - [domains_check_MT.py:46] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000217D051D490>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:35:42 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:35:43 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:35:43 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:35:44 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:45 - ERROR - [domains_check_MT.py:46] - Request error for googleblog.com: HTTPConnectionPool(host='googleblog.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:45 - ERROR - [domains_check_MT.py:46] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:46 - ERROR - [domains_check_MT.py:46] - Request error for tinyurl.com: HTTPSConnectionPool(host='tinyurl.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:46 - ERROR - [domains_check_MT.py:46] - Request error for weebly.com: HTTPConnectionPool(host='weebly.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for mozilla.org: HTTPSConnectionPool(host='mozilla.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for flickr.com: HTTPSConnectionPool(host='flickr.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for googleblog.com: HTTPConnectionPool(host='googleblog.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:47 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:48 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:35:48 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:17 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001A633BA44D0>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:40:17 - ERROR - [domains_check_MT.py:46] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001A633BC6D20>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:40:17 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:18 - ERROR - [domains_check_MT.py:46] - Request error for apple.com: HTTPSConnectionPool(host='www.apple.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:18 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:18 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:19 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:40:20 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:40:20 - ERROR - [domains_check_MT.py:46] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001A634032A50>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:40:20 - ERROR - [domains_check_MT.py:46] - Request error for archive.org: HTTPConnectionPool(host='archive.org', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:21 - ERROR - [domains_check_MT.py:46] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001A6351FBEC0>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-11 22:40:22 - ERROR - [domains_check_MT.py:46] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-11 22:40:22 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:22 - ERROR - [domains_check_MT.py:46] - Request error for googleblog.com: HTTPSConnectionPool(host='googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:24 - ERROR - [domains_check_MT.py:46] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:25 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for mozilla.org: HTTPSConnectionPool(host='mozilla.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for sites.google.com: HTTPConnectionPool(host='sites.google.com', port=80): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for cdc.gov: HTTPSConnectionPool(host='cdc.gov', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for baidu.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for open.spotify.com: HTTPSConnectionPool(host='open.spotify.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for spotify.com: HTTPSConnectionPool(host='open.spotify.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:26 - ERROR - [domains_check_MT.py:46] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:27 - ERROR - [domains_check_MT.py:46] - Request error for doi.org: HTTPSConnectionPool(host='www.doi.org', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:27 - ERROR - [domains_check_MT.py:46] - Request error for qq.com: HTTPSConnectionPool(host='www.qq.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:30 - ERROR - [domains_check_MT.py:46] - Request error for amazonaws.com: HTTPSConnectionPool(host='aws.amazon.com', port=443): Read timed out. (read timeout=0.5)
None
2024-12-11 22:40:34 - ERROR - [domains_check_MT.py:46] - Request error for amazonaws.com: HTTPSConnectionPool(host='aws.amazon.com', port=443): Read timed out. (read timeout=0.5)
None
